# ─── Configuration Serveur ──────────────────────────────────────────────────
server.port=${SERVER_PORT}
spring.application.name=notification-service

# ─── Configuration Oracle ──────────────────────────────────────────────────
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ─── Configuration JPA / Hibernate ──────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ─── Sécurité Keycloak ──────────────────────────────────────────────────────
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}

# ─── Configuration Kafka ────────────────────────────────────────────────────
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# Désérialisation robuste
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.gerai.notificationservice.event.NotificationEvent

spring.kafka.listener.missing-topics-fatal=false
app.kafka.topic.notifications=notification-events

# ─── Configuration Async (emails) ───────────────────────────────────────────
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=email-async-

# ─── Configuration Email (SMTP) ─────────────────────────────────────────────
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=${SMTP_USER}

app.mail.enabled=true

# ─── Logs ───────────────────────────────────────────────────────────────────
logging.level.com.gerai.notificationservice=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.mail=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.kafka=INFO