-- ============================================================
-- MIGRATION: Leave types v2 — Tunisian regulations
-- Run once on GERAI schema before service restart
-- ============================================================

-- 1. New leave types (IDs 8-15)
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (8,  'FAMILIAL');
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (9,  'HAJJ');
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (10, 'POSTNATAL');
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (11, 'ALLAITEMENT');
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (12, 'LONGUE_MALADIE');
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (13, 'NAISSANCE_PERE');
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (14, 'CREATION_ENTREPRISE');
INSERT INTO GERAI.LEAVE_TYPES (LEAVE_TYPE_ID, NAME) VALUES (15, 'OBLIGATIONS_LEGALES');

-- 2. New columns on LEAVE_REQUESTS (Hibernate update adds them too, but explicit DDL sets correct NOT NULL/DEFAULT)
ALTER TABLE GERAI.LEAVE_REQUESTS ADD HALF_SALARY NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE GERAI.LEAVE_REQUESTS ADD MED_APPROVED NUMBER(1);
ALTER TABLE GERAI.LEAVE_REQUESTS ADD MED_APPROVED_AT TIMESTAMP;
ALTER TABLE GERAI.LEAVE_REQUESTS ADD MED_APPROVED_BY NUMBER;
ALTER TABLE GERAI.LEAVE_REQUESTS ADD MED_COMMENT VARCHAR2(500);

-- 3. Career-usage tracking (once-in-career leaves: HAJJ)
CREATE TABLE GERAI.CAREER_LEAVE_USED (
    ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID  NUMBER NOT NULL,
    LEAVE_TYPE_ID NUMBER NOT NULL,
    REQUEST_ID   NUMBER NOT NULL,
    USED_DATE    DATE DEFAULT SYSDATE,
    CONSTRAINT uk_career_leave UNIQUE (EMPLOYEE_ID, LEAVE_TYPE_ID)
);

-- 4. Public holidays (Tunisia — recurring stored as canonical dates)
CREATE TABLE GERAI.PUBLIC_HOLIDAYS (
    HOLIDAY_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HOLIDAY_DATE DATE          NOT NULL,
    LABEL        VARCHAR2(100) NOT NULL,
    RECURRING    NUMBER(1)     DEFAULT 1
);

INSERT INTO GERAI.PUBLIC_HOLIDAYS (HOLIDAY_DATE, LABEL) VALUES (DATE '2026-01-01', 'Nouvel An');
INSERT INTO GERAI.PUBLIC_HOLIDAYS (HOLIDAY_DATE, LABEL) VALUES (DATE '2026-03-20', 'Fête de l''Indépendance');
INSERT INTO GERAI.PUBLIC_HOLIDAYS (HOLIDAY_DATE, LABEL) VALUES (DATE '2026-04-09', 'Jour des Martyrs');
INSERT INTO GERAI.PUBLIC_HOLIDAYS (HOLIDAY_DATE, LABEL) VALUES (DATE '2026-05-01', 'Fête du Travail');
INSERT INTO GERAI.PUBLIC_HOLIDAYS (HOLIDAY_DATE, LABEL) VALUES (DATE '2026-07-25', 'Fête de la République');
INSERT INTO GERAI.PUBLIC_HOLIDAYS (HOLIDAY_DATE, LABEL) VALUES (DATE '2026-08-13', 'Fête de la Femme');
INSERT INTO GERAI.PUBLIC_HOLIDAYS (HOLIDAY_DATE, LABEL) VALUES (DATE '2026-10-15', 'Fête de l''Évacuation');

COMMIT;
