spring:
  application:
    name: grh-backend

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI}
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: ${KC_REDIRECT_URI}
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI}
            user-name-attribute: preferred_username

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

keycloak:
  server-url: ${KC_SERVER_URL}
  realm: master
  admin-realm: master
  admin-client-id: admin-cli
  admin-username: ${KC_ADMIN_USERNAME}
  admin-password: ${KC_ADMIN_PASSWORD}
  target-realm: ${KC_TARGET_REALM}

server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true